name: Laravel Vue Ecommerce CI/CD

env:
  APP_ENV: testing
  APP_DEBUG: true
  DB_CONNECTION: sqlite
  DB_DATABASE: database/database.sqlite
  PROJECT_NAME: "Laravel Vue Ecommerce"
  ENVIRONMENT: "production"

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
      - uses: actions/checkout@v4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Steps Node Js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install Node Dependencies
        run: npm ci
      - name: Build Assets
        run: npm run build
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: ./vendor/bin/phpunit --dont-report-useless-tests

      # - name: Run Style Check
      #   run: vendor/bin/phpcs --standard=PSR12 app/

      # - name: Run Security Checker
      #   run: vendor/bin/security-checker security:check composer.lock

      # - name: Run Deprecation Checker
      # #   run: vendor/bin/deprecation-detector detect:run src/

      - name: Run Laravel Pint
        run: vendor/bin/pint --test
      # - name: Run PHPStan
      #   run: vendor/bin/phpstan analyse --level=7 --memory-limit=2G

      # ðŸ”” Build failed
      - name: Notify Slack (Build Failed)
        if: failure()
        run: |
          bash .github/scripts/slack-notify.sh \
            build failed \
            "${{env.PROJECT_NAME}}" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # ðŸ”” Build success
      - name: Notify Slack (Build Success)
        if: success()
        run: |
          bash .github/scripts/slack-notify.sh \
            build success \
            "${{env.PROJECT_NAME}}" \
            "${{ github.ref_name }}" \
            "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
