name: Laravel Vue API Axios E-Commerce Application CI/CD

on:
  push:
    branches: ["main"]

jobs:
  laravel-ecommerce-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: laravel
          MYSQL_USER: sail
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout repository code
      - uses: actions/checkout@v4

      # * set up the Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run Laravel Docker container
        run: |
          docker build -t laravel-app .
          docker run -d --name laravel-app --link ${{ job.services.mysql.id }}:mysql -p 8000:8000 -e DB_CONNECTION=mysql -e DB_HOST=mysql -e DB_PORT=3306 -e DB_DATABASE=laravel -e DB_USERNAME=sail -e DB_PASSWORD=password laravel-app

      # 2. Setup PHP environment
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"

      # 3. Get Composer cache directory
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      # 4. Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # 5. Prepare environment file
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # 6. Install PHP dependencies
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # 7. Generate application key
      - name: Generate key
        run: php artisan key:generate

      # 8. Set directory permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
